#!/bin/bash

# Distributed Customer API Demo Script
# Shows both legacy and distributed modes

echo "🚀 Customer API - Gleam OTP Application with Distributed Supervisor"
echo "=================================================================="
echo ""
echo "This demo showcases a Gleam application with Horde-like distributed"
echo "supervisor functionality for fault-tolerant customer management."
echo ""

echo "📁 Enhanced Project Structure:"
echo "├── src/"
echo "│   ├── customer_api.gleam           # Main application (mode-aware)"
echo "│   ├── distributed_customer_api.gleam  # Distributed mode demo"
echo "│   ├── customer.gleam               # Customer data model" 
echo "│   ├── customer_actor.gleam         # Customer service (legacy + distributed)"
echo "│   ├── database.gleam               # In-memory database"
echo "│   ├── distributed_supervisor.gleam # Horde-like distributed supervisor ✨"
echo "│   ├── app_supervisor.gleam         # Application supervisor ✨"
echo "│   └── config.gleam                 # Configuration management ✨"
echo "├── test/"
echo "│   ├── customer_api_test.gleam      # Legacy unit tests"
echo "│   └── distributed_supervisor_test.gleam # Distributed tests ✨"
echo "├── ARCHITECTURE.md                  # Updated architecture guide"
echo "└── README.md                        # Documentation"
echo ""

echo "🏗️ Architecture Components:"
echo ""
echo "1. Customer Data Model (src/customer.gleam):"
echo "   - Type-safe customer representation"
echo "   - Optional fields with proper handling"
echo "   - Data validation and serialization"
echo ""

echo "2. Database Layer (src/database.gleam):"
echo "   - In-memory storage with Dict"
echo "   - Full CRUD operations"
echo "   - Email uniqueness validation"
echo "   - Immutable state updates"
echo ""

echo "3. Customer Service (src/customer_actor.gleam):"
echo "   - Legacy service layer (functional API)"
echo "   - Distributed service with OTP actors ✨"
echo "   - Error handling and propagation"
echo "   - State management with supervision ✨"
echo ""

echo "4. Distributed Supervisor (src/distributed_supervisor.gleam): ✨"
echo "   - Horde-like distributed process management"
echo "   - Consistent hashing for actor distribution"
echo "   - Automatic node discovery and monitoring"
echo "   - Fault tolerance with failover"
echo "   - Real-time cluster status monitoring"
echo "   - Graceful node shutdown with actor migration ✨"
echo "   - Zero-downtime maintenance and scaling ✨"
echo ""

echo "5. Configuration (src/config.gleam): ✨"
echo "   - Environment-based configuration"
echo "   - Support for both legacy and distributed modes"
echo "   - Flexible cluster configuration"
echo ""

echo "🎯 Demo Options:"
echo ""
echo "1. Legacy Mode (Original Functionality):"
echo "   gleam run"
echo ""
echo "2. Distributed Mode (New Horde-like Features): ✨"
echo "   DISTRIBUTED_MODE=true gleam run"
echo ""
echo "3. Custom Cluster Configuration: ✨"
echo "   export DISTRIBUTED_MODE=true"
echo "   export CLUSTER_NODES=\"node1@localhost,node2@localhost,node3@localhost\""
echo "   export HASH_RING_SIZE=512"
echo "   gleam run"
echo ""
echo "4. Run Tests:"
echo "   gleam test                                    # All tests"
echo "   gleam test -- --module distributed_supervisor_test  # Distributed tests only"
echo ""

echo "🌟 Key Features Demonstrated:"
echo ""
echo "Legacy Features:"
echo "• Type-safe functional programming with Gleam"
echo "• Immutable data structures and state management"
echo "• Error handling with Result types"
echo "• Database abstraction layer"
echo "• Comprehensive testing strategy"
echo ""
echo "NEW Distributed Features: ✨"
echo "• Distributed supervisor with Horde-like functionality"
echo "• OTP actor system with proper supervision"
echo "• Consistent hashing for load distribution"
echo "• Automatic node discovery and cluster membership"
echo "• Fault tolerance with automatic failover"
echo "• Real-time cluster monitoring and status reporting"
echo "• Configuration management for distributed operation"
echo "• Graceful node shutdown with zero-downtime actor migration ✨"
echo "• State preservation across node boundaries ✨"
echo ""

echo "🔄 Production Readiness:"
echo ""
echo "Completed Features: ✅"
echo "• OTP Dependencies added (gleam_otp, gleam_erlang)"
echo "• Real OTP actors with proper supervision"
echo "• Distributed supervisor with consistent hashing"
echo "• Cluster membership and fault tolerance"
echo "• Configuration management"
echo "• Comprehensive testing"
echo "• Graceful node shutdown with actor migration ✨"
echo "• Zero-downtime maintenance and scaling ✨"
echo ""
echo "Next Steps for Full Production:"
echo "• Add REST API handlers with Wisp framework"
echo "• Replace in-memory database with SQLite/PostgreSQL"
echo "• Add authentication and authorization"
echo "• Add monitoring and observability"
echo "• Add Docker containerization"
echo ""

echo "📡 Future API Endpoints (Designed for Distributed System):"
echo "GET    /api/customers           # List all customers (distributed)"
echo "POST   /api/customers           # Create new customer (auto-distributed)"
echo "GET    /api/customers/:id       # Get customer by ID (location-aware)"
echo "PUT    /api/customers/:id       # Update customer (distributed state)"
echo "DELETE /api/customers/:id       # Delete customer (cluster-aware)"
echo "GET    /api/cluster/status      # Cluster health and distribution ✨"
echo "GET    /api/cluster/nodes       # Active cluster members ✨"
echo "POST   /api/cluster/rebalance   # Trigger manual rebalancing ✨"
echo ""

echo "🎉 This demonstrates a production-ready foundation for building"
echo "distributed, fault-tolerant customer management systems using:"
echo "• Gleam's type safety and functional programming"
echo "• OTP's battle-tested actor model and supervision"
echo "• Horde-inspired distributed process management"
echo "• BEAM VM's legendary reliability and concurrency"
echo ""
echo "Try it out with: DISTRIBUTED_MODE=true gleam run"
echo ""
echo "See README.md and ARCHITECTURE.md for complete technical details!"